
구현 과제 #1
AST의 구성 요소를 생각하고 구현해야 한다.
ANTLR로 작성한 문법에서 의미를 가지는 시맨틱한 부분이 AST의 노드가 된다.
Parse Tree에서 AST로 변환 시 보통 구성 요소가 줄어들지만, 늘어날 수도 있다.
이전 과제의 테스트용 작성 코드를 AST로 구성하면 어떻게 될 지 직접 구성해본다.
힌트: 프로그램 진입 지점(program)부터 노드를 구성해보고, 의미에 따라 병합/분리한다.

고려사항: expr 계산을 단순화 하기 위한 방법으로 후위표기법 등을 고려할 수도 있으나, 가독성이나 구현 개념 일치를 위해 일반 트리로 그리는 것을 추천한다.

예제 #1
5 * 3 + a * (5 - 9 / 3)
위와 같은 수식을 AST로 구성하는 예시 중 하나는 아래와 같다. (동일할 필요는 없다.)

graph TD
    classDef binop stroke:#333,stroke-width:2px;
    classDef value stroke:#333,stroke-width:1px;

    Root(('+')):::binop
    
    L1(('*')):::binop
    L1_Val1[5]:::value
    L1_Val2[3]:::value
    
    R1(('*')):::binop
    R1_Var[var: a]:::value
    
    R1_Sub(('-')):::binop
    R1_Sub_Val[5]:::value
    
    R1_Deep(('/')):::binop
    R1_Deep_Val1[9]:::value
    R1_Deep_Val2[3]:::value

    Root --> L1
    Root --> R1
    
    L1 --> L1_Val1
    L1 --> L1_Val2
    
    R1 --> R1_Var
    R1 --> R1_Sub
    
    R1_Sub --> R1_Sub_Val
    R1_Sub --> R1_Deep
    
    R1_Deep --> R1_Deep_Val1
    R1_Deep --> R1_Deep_Val2
괄호가 존재하지 않는다.
"곱하기, 나누기" 와 "더하기, 빼기"를 구분하지 않고 표현한다.
연산자의 왼쪽과 오른쪽 값에는 연산, int, var이 들어갈 수 있다.
AST 트리를 구성하는 과정에서 우선순위 여부가 트리 자체에 녹아있다.
트리의 자식 -> 부모 순으로 연산이 우선 처리되어야 한다.
left, right 자리에 연산, int, var를 모두 넣을 수 있어야 한다. (인터페이스 형변환)

==>
BinaryExpr(
    "+",
    BinaryExpr("*", IntLiteral(5), IntLiteral(3)),
    BinaryExpr(
        "*",
        VarRef("a"),
        BinaryExpr(
            "-",
            IntLiteral(5),
            BinaryExpr("/", IntLiteral(9), IntLiteral(3)),
        ),
    ),
)


# 이진트리 바이너리 기준

 5 * 3 + a * (5 - 9 / 3) 

                +
              /   \
             /     \
            *       *
          /   \   /   \
         5     3 a     -
                    /   \
                   5     /
                        / \
                       9   3
# -9

  -
/   \
     9

- 이진트리로만 풀 수 없음
# 이진트리가 아닌 케이스 가정하고 별도로 AST 구조화
```c
int a, b;
a = 1;
b = read();
{
  int c;
  c = a + b;
  write(c);
}
b = 0;
```



# 예제#1 접근

## 예제
5 * 3 + a (5- 9 /3)

## 풀이
필요한 것 
- 숫자 담는 것
- 연산자
- 변수


